export const projectDatas = [
  {
    id: '1',
    title: 'Birrussment API',
    body: 'This is a REST API project required by the Birrussment platform (Website-based application for screening/early detection of speech delay in children). This project was also used for my final year project at University together with 1 of my colleagues',
    techStack: [''],
    image: '/images/projects/1-birrussment-api.png',
    url: 'https://birrussment.com',
  },
  {
    id: '2',
    title: 'Birrussment Admin',
    body: 'Admin panel required by the Birrussment platform. The purpose of this website is to help administrators in management users, Assessment questions, and Assessment results from early detection applications speech delay',
    techStack: [''],
    image: '/images/projects/2-admin-birrussment.png',
    url: '',
  },
  {
    id: '3',
    title: 'Discuss-IT',
    body: 'A community Q&A platform website on programming and technology-related topics. This project is one of the submissions at the IDCamp x Dicoding Program',
    techStack: [''],
    image: '/images/projects/3-discuss-it.png',
    url: 'https://discuss-it.vercel.app/',
  },
  {
    id: '4',
    title: 'SecondHand',
    body: 'An e-commerce platform for buying and selling secondhand goods. This project is the capstone project of the MSIB program at Binar Academy in the year 2022.',
    techStack: [''],
    image: '/images/projects/4-secondhand.png',
    url: 'https://secondhandfe.vercel.app/',
  },
  {
    id: '5',
    title: 'Irememo',
    body: 'Website for storing digital notes. Apart from adding notes, you can also edit, delete and archive notes. This project is one of the submissions at the IDCamp x Dicoding Program',
    techStack: [''],
    image: '/images/projects/5-irememo.png',
    url: 'https://irememo.vercel.app/',
  },
  {
    id: '6',
    title: 'Kitchenset Cibubur',
    body: 'This is one of the client’s freelance projects that is displayed publicly built with WordPress and Elementor. This is a simple development but provides quite a challenge for copywriting',
    techStack: [''],
    image: '/images/projects/6-kitchensetcibubur.png',
    url: 'https://kitchensetcibuburmurah.com/',
  },
  {
    id: '7',
    title: 'rumahterapialbirru.com',
    body: 'This is one of the client’s freelance projects that is displayed publicly built with Next.js',
    techStack: [''],
    image: '/images/projects/7-albirru.png',
    url: 'https://rumahterapialbirru.com',
  },
  {
    id: '8',
    title: 'nazwantherapycenter.com',
    body: 'This is one of the client’s freelance projects that is displayed publicly built with Next.js',
    techStack: [''],
    image: '/images/projects/8-nazwan-therapy-center.png',
    url: 'https://nazwantherapycenter.com/',
  },
  {
    id: '9',
    title: 'Programming Knowledge Blogging',
    body: 'a site to find the latest and most trusted programming articles. This project became the 3rd Winner in the Mini-Hackaton (Unlocking HER Potentials, Woman In Tech) held by Web Programming Unpas (WPU)',
    techStack: [''],
    image: '/images/projects/9-minihackathon.png',
    url: 'https://programmingknowledge-jamaica.vercel.app',
  },
  {
    id: '10',
    title: 'BCR Landing Page',
    body: 'This landing page is one of the MSIB program at Binar Academy in the year 2022.',
    techStack: [''],
    image: '/images/projects/10-bcr.png',
    url: 'https://silvianaim02.github.io/Binar-Car-Rental',
  },
];
